### ISSUE TITLE
wasmtime tutorial does not work ("error opening input test.txt: Bad file descriptor")

### ISSUE THREAD

**Issue by Keno** [CraneStation/wasmtime#88] opened 2019-03-31 22:02 UTC
I tried to follow [the tutorial](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-tutorial.md), but ran into an error trying to read the input file:

```
$ ~/wasmtime/target/release/wasmtime ./a.out ./test.txt /tmp/somewhere.txt
error opening input ./test.txt: Bad file descriptor
```
The same error occurs if I try to run the next command in the tutorial to expose the capabilities:
```
~/wasmtime/target/release/wasmtime --dir=. --dir=/tmp a.out test.txt /tmp/somewhere.txt
error opening input test.txt: Bad file descriptor
```
The usage message does work fine if I give it the wrong arguments, so I would suspect the problem is with the open call:
```
~/wasmtime/target/release/wasmtime --dir=. --dir=/tmp a.out
usage: a.out <from> <to>
```

My wasmtime version is a6f31a2be331f66a26e5516cae80c02261b49744 and my wasi-sdk version is https://github.com/CraneStation/wasi-sdk/commit/0ee2a7cd6aceff835cc4d954baa8302f52ae496c (both built from source).

**Comment by sunfishcode** [comment] 2019-03-31 23:28
Thanks for the report! It looks like the problem is that the wasi-sdk repo is referencing an outdated revision of wasi-sysroot. I'll have a fix for this soon.

**Comment by sunfishcode** [comment] 2019-04-01 00:07
https://github.com/CraneStation/wasi-sdk/pull/7 is now open.

**Closed** 2019-04-01 16:28 UTC
